### ISSUE TITLE
[Bug]: Cannot navigate between duplicate videos in playlist

### ISSUE THREAD

**Issue by kommunarr** [PikachuEXE/FreeTube#57]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Save the same video twice to the same playlist
2. Open that video in the playlist from the Playlist tab
3. Try to click on duplicate video entry: encounter bug
4. Try to click on "Play next video" button: encounter bug
5. Skip to end of video and try to let video autoplay: encounter bug

![Screenshot_20230908_225808](https://github.com/PikachuEXE/FreeTube/assets/84899178/fe75f67e-83c3-461f-9f24-13ceb7a4a265)

### Expected Behavior

The duplicate video can be navigated to normally in any case.

Dev notes:
I would reckon this is happening because the videos have the same route. If that's the case, you'll have to add some dupe differentiator to the route (e.g., `&duplicate-count={number}`).

### Issue Labels

usability issue

### FreeTube Version

402af7a2f885aed8e72c808aca844c97bff8a3f7

### Operating System Version

OpenSUSE Tumbleweed

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by PikachuEXE** [comment]
Fixed in 6e7a627902847a6a242b0740565960a83100e007

**Comment by kommunarr** [comment]
~While this appears to be fixed for created playlists, I am still encountering the issue with the Favorites playlist.~

Edit: It worked once, but now I'm still encountering it on created playlists. The bug is "fixed" in that you can try to navigate to a duplicate if you select the first duplicate in the playlist. But then the UI shows that the first duplicate is still the active playlist video, and you can't navigate to the other duplicates anymore. Tested with a playlist comprised of one video duplicated three times.

**Comment by PikachuEXE** [comment]
I have only fixed the clicking on links in https://github.com/PikachuEXE/FreeTube/commit/6e7a627902847a6a242b0740565960a83100e007

Please confirm if it's fixed or not first

I will try to take a look at `Play next video` which needs more changes (and probably more complicated)

**Comment by kommunarr** [comment]
To clarify, I'm still experiencing the issue when clicking on links in the watch-video-playlist box.

**Comment by PikachuEXE** [comment]
Cannot reproduce
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/297b329e-2196-426e-8dbd-1aaccdce7e7b)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/e78c236b-e791-4d99-a483-c656e2088756)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/8f31d96e-d8dd-466a-96ce-028ad33784d2)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/508d0d11-4bc9-424a-bb4b-15e507888981)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/cb2b3f03-5511-459e-89a9-904c10f1b9e4)

Videos: 
- https://youtu.be/qAE5KoyFEUo
- https://youtu.be/jJlfOhQ_f1M

Even I just create another new playlist now with duplicate I have no issue

Not to mention I might have also fixed play next/prev video in https://github.com/PikachuEXE/FreeTube/commit/66e3dbe7ac3a0313d15adf6eb25464fcccd9536d

Might need help from @efb4f5ff-1298-471a-8973-3d47447115dc

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> ave the same video twice to the same playlist
> Open that video in the playlist from the Playlist tab
> Try to click on duplicate video entry: encounter bug

Did not get a bug but on clicking on nr 4 it went to play nr 4 so i thought but i actually just reloaded nr 3

![Capture](https://github.com/PikachuEXE/FreeTube/assets/73130443/88528daa-326e-4179-a4d5-253cb055c18a)


> Try to click on "Play next video" button: encounter bug

When i got to this step it actually played nr 4

> Skip to end of video and try to let video autoplay: encounter bug

no error here

**Comment by PikachuEXE** [comment]
> Did not get a bug but on clicking on nr 4 it went to play nr 4 so i thought but i actually just reloaded nr 3

In watch page? or from local playlist view (inside a playlist)? or something else

Let me test both tomorrow

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is on the watch page

**Comment by PikachuEXE** [comment]
I have tried both (from single local playlist view) & watch page on a playlist with duplicate videos
I clicked on non 1st video (2nd/3rd) and also 1st video to compare the results

The playlist component is showing correct entry being played
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/918f9007-6172-4455-855a-59db1940adea)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/c5983413-f6f2-4aba-be4b-fae64ca65f93)
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/58cc8baa-a8bc-478d-9828-1eb51de9bda8)

So for me it's cannot be reproduced anymore (after fix)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Still get the bug im on https://github.com/PikachuEXE/FreeTube/commit/bdb2a942f623b0adeb8a83823ec314d4775913b5

https://github.com/PikachuEXE/FreeTube/assets/73130443/b52ed477-70c4-4b51-889f-f43874b74464

**Comment by PikachuEXE** [comment]
OK I see what's wrong
The URLs in different links are different
Fixing...
![image](https://github.com/PikachuEXE/FreeTube/assets/1018543/cf0da6bb-7ff1-4c07-825f-e6cd267371ae)

**Comment by PikachuEXE** [comment]
Fixed in https://github.com/PikachuEXE/FreeTube/commit/25c75ce7fb211e1c24bf01ad6cd383abff0f1521

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm that its fixed. Just to confirm @jasonhenriquez did u experience the same as me when it didn't work or is there still something that needs to be addressed?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez

**Comment by kommunarr** [comment]
Got this error while moving a duplicate video up in a playlist using the arrow button. But otherwise, looks good
![Screenshot_20231021_061747](https://github.com/PikachuEXE/FreeTube/assets/84899178/1c012d5c-cfab-4756-baaf-fdfd345ff813)

**Comment by PikachuEXE** [comment]
I think that's one of the callback errors from player after you switch back from watch video view
Please try it without watching any video

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
can be closed btw
